# FROM python:3.7.17-alpine3.18
FROM python:3.7.17-slim
# FROM python:3.7.17-bullseye

# COPY ./requirements.txt ./

# WORKDIR /app

RUN pip install --upgrade pip

# CMD ["gunicorn", "-b", "0.0.0.0:80", "app:server"]